# Copyright (c) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#

name: Docs only check

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  check_and_label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Check docs only
        run: |
          non_doc_files_changed=( $(git diff --name-only origin/main | sed '/docs\//d') )
          num_non_docs=${#non_doc_files_changed[@]}
          if [ "$num_non_docs" == "0" ]; then
            echo "non_docs=$non_doc_files_changed" >> $GITHUB_ENV
            echo "is_docs_only=true" >> $GITHUB_ENV
          else
            echo "is_docs_only=false" >> $GITHUB_ENV
          fi

      - name: Add label
        uses: actions-ecosystem/action-add-labels@v1
        if: env.is_docs_only
        with:
          labels: 
            force-skip-ci
