# Copyright (c) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#

name: Docs only check

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

env:
  is_docs_only: true

jobs:
  check_and_label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
        with:
          ref: ${{ github.head_ref }}
      
      - name: Remove label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: force-skip-ci
          
      - name: Get files changed
        uses: jitterbit/get-changed-files@v1
        
      - name: Check docs only
        run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            if [[ ! "${changed_file}" =~ "docs/" ]]; then
              echo "is_docs_only=false" >> $GITHUB_ENV
            fi
          done

        
      - name: Add label
        if: ${{ env.is_docs_only == 'true' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: 
            force-skip-ci
