# Copyright (c) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#

name: Docs only check

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

env:
  is_docs_only: true

jobs:
  check_and_label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Remove label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: force-skip-ci
          
      - name: Get files changed
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            !docs/*
            
      - name: Check docs only
        run: |
          for changed_file in $changed_files; do
            echo "$changed_file"
            if [[ env.GIT_DIFF ]]; then
              echo "is_docs_only=true" >> $GITHUB_ENV
            fi
          done
        
      - name: Add label
        if: ${{ env.is_docs_only == 'true' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: 
            force-skip-ci
