# Copyright (c) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#

name: Docs only check

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  check_and_label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
        with:
          ref: ${{ github.head_ref }}
        
      - name: Check docs only
        run: |
          git fetch origin main
          non_doc_files_changed=$((git fetch origin main:main) && (git diff --name-only main | sed '/docs\//d'))
          if [ "$non_doc_files_changed" ]; then
            echo "is_docs_only=false" >> $GITHUB_ENV
          else
            echo "is_docs_only=true" >> $GITHUB_ENV
          fi

      - name: Add label
        if: ${{ env.is_docs_only == 'true' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: 
            force-skip-ci
