# Copyright (c) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#

name: Docs only check

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  check_and_label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check docs only
        run: echo "non_doc_files_changed=$(git diff --name-only origin/main | sed '/docs\//d')" >> $GITHUB_ENV

      - name: Add label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ env.non_doc_files_changed == '0' }}
        with:
          labels: 
            force-skip-ci
