# Copyright (c) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#

name: Docs only check

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  check_and_label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
        with:
          ref: ${{ github.head_ref }}
      
      - name: Remove label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: force-skip-ci
          
      - name: Get files changed
        uses: jitterbit/get-changed-files@v1
        
      - name: Check docs only
        run: | 
          non_docs=$(sed '/docs\//d' ${{ steps.files.outputs.all }})
          num_non_docs=${#non_docs[@]}
          if [ "$num_non_docs" = "0" ]; then
            echo "is_docs_only=true" >> $GITHUB_ENV
            echo "$non_doc_files_changed"
          else
            echo "is_docs_only=false" >> $GITHUB_ENV
            echo "$non_doc_files_Changed"
          fi
        
      - name: Add label
        if: ${{ env.is_docs_only == 'true' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: 
            force-skip-ci
